<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Together.Application\Together.Application.csproj" />
    <ProjectReference Include="..\Together.Contract\Together.Contract.csproj" />
    <ProjectReference Include="..\Together.Infrastructure\Together.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
